baseURL = "https://www.kenleidal.com/"
languageCode = "en-us"
title = "Ken Leidal"
theme = "minimal"
disqusShortname = "kkleidal" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Ken Leidal"
    description = "Systems Architect, AI/ML Researcher, Entrepreneur"
    profilePic = "https://avatars0.githubusercontent.com/u/5483015?s=400&u=0ce3c4b588d6f5f30c8ec216b6d3e47c8b28f5c8&v=4"
    githubUsername = "kkleidal"
    accent = "#BA211C"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/resume"
    name = "Resume"
    weight = 2

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:kkleidal@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/kkleidal/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/kkleidal/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/kkleidal/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://keybase.io/kkleidal"
    name = "key"
    weight = 5

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
